version: 0.0
os: linux
files:
   - source: /
     destination: /usr/local/nginx/html
permissions:
   - object: /usr/local/nginx/html
     pattern: "**"
     owner: apache
     group: apache
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: scripts/restartapache.sh
      runas: root
   AfterInstall:
    - location: scripts/restartapache.sh
      runas: root
